/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedManajemenUserRouteImport } from './routes/_authenticated/manajemen-user'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedKodeCutiRouteImport } from './routes/_authenticated/kode-cuti'
import { Route as AuthenticatedVerifikasiIndexRouteImport } from './routes/_authenticated/verifikasi/index'
import { Route as AuthenticatedPegawaiIndexRouteImport } from './routes/_authenticated/pegawai/index'
import { Route as AuthenticatedCutiIndexRouteImport } from './routes/_authenticated/cuti/index'
import { Route as AuthenticatedVerifikasiBawahanRouteImport } from './routes/_authenticated/verifikasi/bawahan'
import { Route as AuthenticatedCutiBuatRouteImport } from './routes/_authenticated/cuti/buat'
import { Route as AuthenticatedCutiIdRouteImport } from './routes/_authenticated/cuti/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManajemenUserRoute =
  AuthenticatedManajemenUserRouteImport.update({
    id: '/manajemen-user',
    path: '/manajemen-user',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKodeCutiRoute = AuthenticatedKodeCutiRouteImport.update({
  id: '/kode-cuti',
  path: '/kode-cuti',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVerifikasiIndexRoute =
  AuthenticatedVerifikasiIndexRouteImport.update({
    id: '/verifikasi/',
    path: '/verifikasi/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPegawaiIndexRoute =
  AuthenticatedPegawaiIndexRouteImport.update({
    id: '/pegawai/',
    path: '/pegawai/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCutiIndexRoute = AuthenticatedCutiIndexRouteImport.update({
  id: '/cuti/',
  path: '/cuti/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVerifikasiBawahanRoute =
  AuthenticatedVerifikasiBawahanRouteImport.update({
    id: '/verifikasi/bawahan',
    path: '/verifikasi/bawahan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCutiBuatRoute = AuthenticatedCutiBuatRouteImport.update({
  id: '/cuti/buat',
  path: '/cuti/buat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCutiIdRoute = AuthenticatedCutiIdRouteImport.update({
  id: '/cuti/$id',
  path: '/cuti/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/kode-cuti': typeof AuthenticatedKodeCutiRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/manajemen-user': typeof AuthenticatedManajemenUserRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/cuti/$id': typeof AuthenticatedCutiIdRoute
  '/cuti/buat': typeof AuthenticatedCutiBuatRoute
  '/verifikasi/bawahan': typeof AuthenticatedVerifikasiBawahanRoute
  '/cuti/': typeof AuthenticatedCutiIndexRoute
  '/pegawai/': typeof AuthenticatedPegawaiIndexRoute
  '/verifikasi/': typeof AuthenticatedVerifikasiIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/kode-cuti': typeof AuthenticatedKodeCutiRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/manajemen-user': typeof AuthenticatedManajemenUserRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/': typeof AuthenticatedIndexRoute
  '/cuti/$id': typeof AuthenticatedCutiIdRoute
  '/cuti/buat': typeof AuthenticatedCutiBuatRoute
  '/verifikasi/bawahan': typeof AuthenticatedVerifikasiBawahanRoute
  '/cuti': typeof AuthenticatedCutiIndexRoute
  '/pegawai': typeof AuthenticatedPegawaiIndexRoute
  '/verifikasi': typeof AuthenticatedVerifikasiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/kode-cuti': typeof AuthenticatedKodeCutiRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/manajemen-user': typeof AuthenticatedManajemenUserRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cuti/$id': typeof AuthenticatedCutiIdRoute
  '/_authenticated/cuti/buat': typeof AuthenticatedCutiBuatRoute
  '/_authenticated/verifikasi/bawahan': typeof AuthenticatedVerifikasiBawahanRoute
  '/_authenticated/cuti/': typeof AuthenticatedCutiIndexRoute
  '/_authenticated/pegawai/': typeof AuthenticatedPegawaiIndexRoute
  '/_authenticated/verifikasi/': typeof AuthenticatedVerifikasiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/kode-cuti'
    | '/laporan'
    | '/manajemen-user'
    | '/profil'
    | '/cuti/$id'
    | '/cuti/buat'
    | '/verifikasi/bawahan'
    | '/cuti/'
    | '/pegawai/'
    | '/verifikasi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/kode-cuti'
    | '/laporan'
    | '/manajemen-user'
    | '/profil'
    | '/'
    | '/cuti/$id'
    | '/cuti/buat'
    | '/verifikasi/bawahan'
    | '/cuti'
    | '/pegawai'
    | '/verifikasi'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/kode-cuti'
    | '/_authenticated/laporan'
    | '/_authenticated/manajemen-user'
    | '/_authenticated/profil'
    | '/_authenticated/'
    | '/_authenticated/cuti/$id'
    | '/_authenticated/cuti/buat'
    | '/_authenticated/verifikasi/bawahan'
    | '/_authenticated/cuti/'
    | '/_authenticated/pegawai/'
    | '/_authenticated/verifikasi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manajemen-user': {
      id: '/_authenticated/manajemen-user'
      path: '/manajemen-user'
      fullPath: '/manajemen-user'
      preLoaderRoute: typeof AuthenticatedManajemenUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kode-cuti': {
      id: '/_authenticated/kode-cuti'
      path: '/kode-cuti'
      fullPath: '/kode-cuti'
      preLoaderRoute: typeof AuthenticatedKodeCutiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/verifikasi/': {
      id: '/_authenticated/verifikasi/'
      path: '/verifikasi'
      fullPath: '/verifikasi/'
      preLoaderRoute: typeof AuthenticatedVerifikasiIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pegawai/': {
      id: '/_authenticated/pegawai/'
      path: '/pegawai'
      fullPath: '/pegawai/'
      preLoaderRoute: typeof AuthenticatedPegawaiIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cuti/': {
      id: '/_authenticated/cuti/'
      path: '/cuti'
      fullPath: '/cuti/'
      preLoaderRoute: typeof AuthenticatedCutiIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/verifikasi/bawahan': {
      id: '/_authenticated/verifikasi/bawahan'
      path: '/verifikasi/bawahan'
      fullPath: '/verifikasi/bawahan'
      preLoaderRoute: typeof AuthenticatedVerifikasiBawahanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cuti/buat': {
      id: '/_authenticated/cuti/buat'
      path: '/cuti/buat'
      fullPath: '/cuti/buat'
      preLoaderRoute: typeof AuthenticatedCutiBuatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cuti/$id': {
      id: '/_authenticated/cuti/$id'
      path: '/cuti/$id'
      fullPath: '/cuti/$id'
      preLoaderRoute: typeof AuthenticatedCutiIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedKodeCutiRoute: typeof AuthenticatedKodeCutiRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedManajemenUserRoute: typeof AuthenticatedManajemenUserRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCutiIdRoute: typeof AuthenticatedCutiIdRoute
  AuthenticatedCutiBuatRoute: typeof AuthenticatedCutiBuatRoute
  AuthenticatedVerifikasiBawahanRoute: typeof AuthenticatedVerifikasiBawahanRoute
  AuthenticatedCutiIndexRoute: typeof AuthenticatedCutiIndexRoute
  AuthenticatedPegawaiIndexRoute: typeof AuthenticatedPegawaiIndexRoute
  AuthenticatedVerifikasiIndexRoute: typeof AuthenticatedVerifikasiIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedKodeCutiRoute: AuthenticatedKodeCutiRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedManajemenUserRoute: AuthenticatedManajemenUserRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCutiIdRoute: AuthenticatedCutiIdRoute,
  AuthenticatedCutiBuatRoute: AuthenticatedCutiBuatRoute,
  AuthenticatedVerifikasiBawahanRoute: AuthenticatedVerifikasiBawahanRoute,
  AuthenticatedCutiIndexRoute: AuthenticatedCutiIndexRoute,
  AuthenticatedPegawaiIndexRoute: AuthenticatedPegawaiIndexRoute,
  AuthenticatedVerifikasiIndexRoute: AuthenticatedVerifikasiIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
